[@ui.messageBox titleKey="testflight.moreinfo"/]
[@ww.textfield labelKey="testflight.api_token" name="api_token" required="true" cssClass="long-field"/]
[@ww.textfield labelKey="testflight.team_token" name="team_token" required="true" cssClass="long-field"/]
[@ww.textfield labelKey="testflight.file" name="file" required="true" cssClass="long-field"/]
[@ww.textfield labelKey="testflight.dsym" name="dsym" cssClass="long-field"/]
[@ww.textarea labelKey="testflight.notes" name="notes" cssClass="long-field"/]
[@ww.textfield labelKey="testflight.distribution_lists" name="distribution_lists" cssClass="long-field"/]
[@ww.checkbox labelKey="testflight.notify" name="notify"/]
[@ww.checkbox labelKey="testflight.replace" name="replace"/]